import type { Locale } from '../i18n';
const en = {
  title: 'Questions & Discussion', anonymous: 'Anonymous', name: 'Name (optional)', comment: 'Question or comment',
  post: 'Post', posting: 'Posting…', reply: 'Reply', cancel: 'Cancel', more: 'Load more', empty: 'No questions yet. Start the discussion.',
  loading: 'Loading…', retry: 'Try again', unavailable: 'Discussion is temporarily unavailable. Please try again later.',
  invalid: 'Enter a comment of 1–3,000 characters and a name of at most 60 characters.',
  rate: 'Too many posts or requests. Please wait before trying again (posting limit: 5 per 10 minutes, 30 per day).',
  duplicate: 'This comment was already posted recently.', parent: 'This conversation is no longer available. Refresh the discussion.',
  note: 'No account needed. Posts and names are public. Please do not include personal information.',
  posted: 'Posted.', replies: 'Replies', replying: 'Replying to', privacy: 'Privacy',
  privacyText: 'Discussions are public. We store the optional display name, comment, reply relationship, section, language and posting time in Supabase. No email or account is required. To limit abuse, our server uses a secret-key hash of the IP address that changes daily; raw IP addresses are not stored in the discussion database. Anti-spam records expire after 48 hours and are removed by an hourly cleanup job. Vercel and Supabase may process connection information under their own policies. Administrators can hide or delete posts; deleting a parent also deletes its replies. Do not post personal information. Display names are unverified and do not establish identity.',
};
type Copy = typeof en;
const rows: Record<Exclude<Locale, 'en'>, string[]> = {
  ja: ['質問・ディスカッション','匿名','名前（任意）','質問・コメント','投稿','投稿中…','返信','キャンセル','さらに表示','まだ投稿はありません。最初の質問をどうぞ。','読み込み中…','再試行','現在ディスカッションを利用できません。時間をおいてお試しください。','本文は1〜3,000文字、名前は60文字以内で入力してください。','投稿・アクセスが多すぎます。時間をおいてお試しください（投稿は10分に5件、1日に30件まで）。','同じ内容が最近投稿されています。','この会話は利用できなくなりました。読み込み直してください。','アカウント不要。投稿と名前は公開されます。個人情報は書かないでください。','投稿しました。','返信','返信先','プライバシー','ディスカッションは公開されます。任意の表示名、本文、返信関係、セクション、言語、投稿日時をSupabaseに保存します。メールアドレスやアカウントは不要です。不正投稿対策では、IPアドレスを秘密鍵付きのハッシュに変換し、日ごとに識別値を変えます。生のIPはDiscussion用DBに保存しません。対策用記録は48時間で期限切れとなり、1時間ごとの削除処理で消去します。VercelとSupabaseは各社の方針に基づいて接続情報を処理する場合があります。管理者は投稿を非表示・削除でき、親投稿の削除時は返信も削除します。個人情報は投稿しないでください。表示名は未認証であり、本人性を保証しません。'],
  fr: ['Questions et discussion','Anonyme','Nom (facultatif)','Question ou commentaire','Publier','Publication…','Répondre','Annuler','Afficher plus','Aucune question. Lancez la discussion.','Chargement…','Réessayer','Discussion temporairement indisponible. Réessayez plus tard.','Saisissez 1 à 3 000 caractères et un nom de 60 caractères maximum.','Trop de requêtes. Patientez (5 publications par 10 minutes, 30 par jour).','Ce commentaire a déjà été publié récemment.','Cette conversation est indisponible. Rechargez la discussion.','Sans compte. Les noms et messages sont publics. Évitez les informations personnelles.','Publié.','Réponses','Réponse à','Confidentialité','Les discussions sont publiques. Supabase conserve le nom facultatif, le texte, les réponses, la section, la langue et la date. Aucun compte ni e-mail requis. La protection antispam utilise un hachage secret de l’adresse IP, renouvelé chaque jour ; aucune IP brute n’est stockée dans la base de discussion. Ces traces expirent après 48 heures et sont supprimées toutes les heures. Vercel et Supabase peuvent traiter les données de connexion selon leurs politiques. Les administrateurs peuvent masquer ou supprimer les messages ; supprimer un parent supprime ses réponses. Ne publiez pas de données personnelles. Les noms ne sont pas vérifiés.'],
  de: ['Fragen und Diskussion','Anonym','Name (optional)','Frage oder Kommentar','Posten','Wird gepostet…','Antworten','Abbrechen','Mehr laden','Noch keine Fragen. Beginne die Diskussion.','Wird geladen…','Erneut versuchen','Die Diskussion ist vorübergehend nicht verfügbar. Bitte später erneut versuchen.','Bitte 1–3.000 Zeichen und einen Namen mit höchstens 60 Zeichen eingeben.','Zu viele Anfragen. Bitte warten (5 Beiträge je 10 Minuten, 30 pro Tag).','Dieser Kommentar wurde kürzlich bereits gepostet.','Diese Unterhaltung ist nicht mehr verfügbar. Bitte neu laden.','Kein Konto nötig. Namen und Beiträge sind öffentlich. Keine persönlichen Daten posten.','Gepostet.','Antworten','Antwort an','Datenschutz','Diskussionen sind öffentlich. Supabase speichert den optionalen Namen, Text, Antworten, Abschnitt, Sprache und Zeitpunkt. Konto und E-Mail sind nicht nötig. Zum Spamschutz verwenden wir einen geheimen, täglich wechselnden IP-Hash; keine rohe IP wird in der Diskussionsdatenbank gespeichert. Schutzdaten verfallen nach 48 Stunden und werden stündlich gelöscht. Vercel und Supabase können Verbindungsdaten gemäß ihren Richtlinien verarbeiten. Administratoren können Beiträge ausblenden oder löschen; beim Löschen eines Elternbeitrags werden Antworten mitgelöscht. Keine persönlichen Daten veröffentlichen. Namen sind nicht verifiziert.'],
  it: ['Domande e discussione','Anonimo','Nome (facoltativo)','Domanda o commento','Pubblica','Pubblicazione…','Rispondi','Annulla','Carica altro','Nessuna domanda. Inizia la discussione.','Caricamento…','Riprova','Discussione temporaneamente non disponibile. Riprova più tardi.','Inserisci da 1 a 3.000 caratteri e un nome di massimo 60 caratteri.','Troppe richieste. Attendi (5 post ogni 10 minuti, 30 al giorno).','Questo commento è già stato pubblicato di recente.','Questa conversazione non è disponibile. Ricarica la discussione.','Nessun account. Nomi e messaggi sono pubblici. Non inserire dati personali.','Pubblicato.','Risposte','Risposta a','Privacy','Le discussioni sono pubbliche. Supabase conserva nome facoltativo, testo, risposte, sezione, lingua e data. Non servono account o e-mail. Per limitare gli abusi usiamo un hash segreto dell’IP che cambia ogni giorno; nessun IP grezzo è salvato nel database delle discussioni. I dati antispam scadono dopo 48 ore e vengono eliminati ogni ora. Vercel e Supabase possono trattare dati di connessione secondo le proprie politiche. Gli amministratori possono nascondere o eliminare post; eliminando il genitore si eliminano anche le risposte. Non pubblicare dati personali. I nomi non sono verificati.'],
  es: ['Preguntas y debate','Anónimo','Nombre (opcional)','Pregunta o comentario','Publicar','Publicando…','Responder','Cancelar','Cargar más','Aún no hay preguntas. Inicia el debate.','Cargando…','Reintentar','El debate no está disponible temporalmente. Inténtalo más tarde.','Introduce de 1 a 3.000 caracteres y un nombre de hasta 60 caracteres.','Demasiadas solicitudes. Espera (5 publicaciones cada 10 minutos, 30 al día).','Este comentario ya se publicó recientemente.','Esta conversación ya no está disponible. Recarga el debate.','Sin cuenta. Los nombres y mensajes son públicos. No incluyas datos personales.','Publicado.','Respuestas','Respuesta a','Privacidad','Los debates son públicos. Supabase guarda el nombre opcional, texto, respuestas, sección, idioma y fecha. No se pide cuenta ni correo. Para evitar abusos usamos un hash secreto de la IP que cambia a diario; no guardamos la IP original en la base de debates. Los registros antispam caducan a las 48 horas y se borran cada hora. Vercel y Supabase pueden procesar datos de conexión según sus políticas. Los administradores pueden ocultar o borrar mensajes; borrar el padre elimina sus respuestas. No publiques datos personales. Los nombres no están verificados.'],
  'zh-CN': ['提问与讨论','匿名','姓名（可选）','问题或评论','发布','发布中…','回复','取消','加载更多','暂无提问，欢迎开始讨论。','加载中…','重试','讨论暂时不可用，请稍后再试。','请输入1至3,000字的正文，姓名最多60字。','发布或请求过于频繁，请稍后再试（每10分钟最多5条，每天30条）。','最近已经发布过相同内容。','该对话已不可用，请重新加载。','无需账号。姓名与内容公开，请勿填写个人信息。','已发布。','回复','回复给','隐私','讨论内容公开。Supabase保存可选姓名、正文、回复关系、章节、语言和时间，无需邮箱或账号。反滥用措施使用带密钥且每日变化的IP哈希，不在讨论数据库中保存原始IP。反垃圾记录48小时后过期，由每小时运行的任务删除。Vercel和Supabase可能依据各自政策处理连接信息。管理员可以隐藏或删除帖子，删除父帖会同时删除回复。请勿发布个人信息，显示姓名未经身份验证。'],
  'zh-TW': ['提問與討論','匿名','姓名（選填）','問題或留言','發布','發布中…','回覆','取消','載入更多','尚無提問，歡迎開始討論。','載入中…','重試','討論暫時無法使用，請稍後再試。','請輸入1至3,000字的內容，姓名最多60字。','發布或請求過於頻繁，請稍後再試（每10分鐘最多5則，每天30則）。','最近已發布過相同內容。','此對話已無法使用，請重新載入。','無需帳號。姓名與內容公開，請勿填寫個人資訊。','已發布。','回覆','回覆給','隱私權','討論內容公開。Supabase儲存選填姓名、內容、回覆關係、章節、語言和時間，無需信箱或帳號。反濫用措施使用帶密鑰且每日變更的IP雜湊，不在討論資料庫儲存原始IP。反垃圾紀錄48小時後過期，由每小時執行的工作刪除。Vercel和Supabase可能依各自政策處理連線資訊。管理員可以隱藏或刪除貼文，刪除父貼文也會刪除回覆。請勿發布個人資訊，顯示姓名未經身分驗證。'],
  ko: ['질문과 토론','익명','이름 (선택)','질문 또는 댓글','게시','게시 중…','답글','취소','더 보기','아직 질문이 없습니다. 토론을 시작하세요.','불러오는 중…','다시 시도','토론을 일시적으로 이용할 수 없습니다. 나중에 다시 시도하세요.','본문은 1~3,000자, 이름은 최대 60자로 입력하세요.','요청이 너무 많습니다. 잠시 기다려 주세요 (10분당 5개, 하루 30개 게시).','최근에 같은 내용이 게시되었습니다.','이 대화를 이용할 수 없습니다. 다시 불러오세요.','계정이 필요 없습니다. 이름과 내용은 공개됩니다. 개인정보를 쓰지 마세요.','게시되었습니다.','답글','답글 대상','개인정보','토론은 공개됩니다. Supabase에 선택한 이름, 본문, 답글 관계, 섹션, 언어와 시간을 저장합니다. 이메일이나 계정은 필요하지 않습니다. 악용 방지를 위해 매일 바뀌는 비밀키 기반 IP 해시를 사용하며, 원본 IP는 토론 데이터베이스에 저장하지 않습니다. 방지 기록은 48시간 후 만료되어 매시간 삭제됩니다. Vercel과 Supabase는 각사의 정책에 따라 연결 정보를 처리할 수 있습니다. 관리자는 게시물을 숨기거나 삭제할 수 있으며, 부모 글 삭제 시 답글도 삭제됩니다. 개인정보를 게시하지 마세요. 표시 이름은 인증되지 않습니다.'],
};
export function discussionMessages(locale: Locale): Copy {
  return locale === 'en' ? en : Object.fromEntries(Object.keys(en).map((key, i) => [key, rows[locale][i]])) as Copy;
}
