export const locales = ['en', 'fr', 'de', 'it', 'es', 'zh-CN', 'zh-TW', 'ja', 'ko'] as const;
export type Locale = typeof locales[number];
export const languageNames: Record<Locale, string> = { en: 'English', fr: 'Français', de: 'Deutsch', it: 'Italiano', es: 'Español', 'zh-CN': '简体中文', 'zh-TW': '繁體中文', ja: '日本語', ko: '한국어' };
export function isLocale(value: string): value is Locale { return locales.includes(value as Locale); }
export function localePath(locale: Locale, path = '/') { return locale === 'en' ? path : `/${locale}${path === '/' ? '' : path}`; }
export function pathLocale(path: string): Locale { const part = path.split('/')[1]; return isLocale(part) ? part : 'en'; }
export function stripLocale(path: string) { return isLocale(path.split('/')[1]) ? path.replace(/^\/[^/]+/, '') || '/' : path; }
export function deviceLocale(languages: readonly string[]): Locale {
  for (const language of languages) {
    if (/^zh/i.test(language)) return /TW|HK|MO|Hant/i.test(language) ? 'zh-TW' : 'zh-CN';
    const base = language.split('-')[0]; if (isLocale(base)) return base;
  } return 'en';
}
const en = {
  chapters: 'Chapters', curiosities: 'Curiosities', about: 'About', privacy: 'Privacy Policy', menu: 'Menu', close: 'Close menu', language: 'Choose language', skip: 'Skip to content', home: 'Home',
  eyebrow: 'A notebook for the curious mind', intro: 'Understand the universe, one idea at a time.', description: 'Free physics notes, from the laws of motion to the frontiers of quantum theory. Follow the mathematics, explore the ideas, and keep asking why.', start: 'Start exploring', chapterIntro: 'Build your understanding, from fundamentals to frontiers.', curiosityIntro: 'Take a closer look at the questions still shaping physics.',
  aboutText: 'Open Physics Notes is a free collection of lecture-style notes covering undergraduate physics and frontier topics. Our goal is clarity, rigor, and accessibility. All content on this site is free to use.', aboutHeading: 'Space to learn. Room to wonder.', aboutDetail: 'Work through the chapters in order, or follow a question that interests you. Equations, explanations, and further reading help connect individual ideas to the bigger picture.',
  updated: 'Last updated', overview: 'Overview', overviewText: 'We collect minimal data for basic site analytics. Personal data is not sold. Data may be shared with service providers as needed to operate analytics and affiliate programs.', cookies: 'Cookies and preferences', cookiesText: 'Cookies may be used for analytics and affiliate tracking. You can disable cookies in your browser settings. Your language preference is stored locally in your browser and can be reset by choosing Same as device.', analytics: 'Analytics', analyticsText: 'If analytics is enabled, page views and aggregated usage metrics may be processed to improve content quality.',
  fallback: 'This article is currently available in English. Translations will be added gradually.', reading: 'Further Reading', affiliate: 'This section may contain affiliate links. If you purchase through these links, Open Physics Notes may earn a commission at no extra cost to you.',
};
type Messages = typeof en;
const translations: Record<Exclude<Locale, 'en'>, string[]> = {
fr: ['Chapitres','À explorer','À propos','Confidentialité','Menu','Fermer le menu','Choisir la langue','Aller au contenu','Accueil','Un carnet pour les esprits curieux','Comprendre l’univers, une idée à la fois.','Des notes de physique gratuites, des lois du mouvement aux frontières de la théorie quantique. Suivez les mathématiques, explorez les idées et continuez à demander pourquoi.','Commencer','Construisez votre compréhension, des bases aux frontières.','Explorez les questions qui façonnent encore la physique.','Open Physics Notes est un recueil gratuit de notes de cours, de la physique universitaire aux sujets de recherche. Notre objectif : clarté, rigueur et accessibilité. Tout le contenu est librement utilisable.','Un espace pour apprendre et s’émerveiller.','Suivez les chapitres dans l’ordre ou explorez une question qui vous intéresse. Équations, explications et lectures complémentaires relient les idées à une vision d’ensemble.','Dernière mise à jour','Présentation','Nous recueillons un minimum de données pour les statistiques du site. Les données personnelles ne sont pas vendues. Elles peuvent être partagées avec les prestataires nécessaires aux statistiques et aux programmes d’affiliation.','Cookies et préférences','Des cookies peuvent servir aux statistiques et au suivi des liens affiliés. Vous pouvez les désactiver dans votre navigateur. La langue choisie est enregistrée localement et peut être réinitialisée avec Same as device.','Statistiques','Si les statistiques sont activées, les pages consultées et les données d’usage agrégées peuvent être traitées pour améliorer le contenu.','Cet article est actuellement disponible en anglais. Les traductions seront ajoutées progressivement.','Pour aller plus loin','Cette section peut contenir des liens affiliés. Un achat via ces liens peut rapporter une commission à Open Physics Notes, sans coût supplémentaire pour vous.'],
de: ['Kapitel','Entdeckungen','Über uns','Datenschutz','Menü','Menü schließen','Sprache wählen','Zum Inhalt','Startseite','Ein Notizbuch für neugierige Menschen','Das Universum verstehen, eine Idee nach der anderen.','Kostenlose Physiknotizen, von den Bewegungsgesetzen bis zu den Grenzen der Quantentheorie. Folgen Sie der Mathematik, erkunden Sie Ideen und fragen Sie weiter nach dem Warum.','Entdecken','Bauen Sie Ihr Verständnis auf – von Grundlagen bis zur Forschung.','Entdecken Sie Fragen, die die Physik bis heute prägen.','Open Physics Notes ist eine kostenlose Sammlung von Vorlesungsnotizen zur Hochschulphysik und aktuellen Forschung. Unser Ziel sind Klarheit, Genauigkeit und Zugänglichkeit. Alle Inhalte können kostenlos genutzt werden.','Raum zum Lernen und Staunen.','Lesen Sie die Kapitel der Reihe nach oder folgen Sie einer interessanten Frage. Gleichungen, Erklärungen und weiterführende Literatur verbinden einzelne Ideen mit dem Gesamtbild.','Zuletzt aktualisiert','Überblick','Wir erheben nur wenige Daten für grundlegende Nutzungsstatistiken. Personenbezogene Daten werden nicht verkauft. Für Analysen und Partnerprogramme können Daten an erforderliche Dienstleister weitergegeben werden.','Cookies und Einstellungen','Cookies können für Analysen und Partnerlinks verwendet werden. Sie können Cookies im Browser deaktivieren. Ihre Spracheinstellung wird lokal im Browser gespeichert und mit Same as device zurückgesetzt.','Nutzungsanalyse','Wenn die Analyse aktiviert ist, können Seitenaufrufe und zusammengefasste Nutzungsdaten zur Verbesserung der Inhalte verarbeitet werden.','Dieser Artikel ist derzeit auf Englisch verfügbar. Übersetzungen werden nach und nach ergänzt.','Weiterführende Literatur','Dieser Abschnitt kann Partnerlinks enthalten. Bei einem Kauf darüber erhält Open Physics Notes möglicherweise eine Provision, ohne zusätzliche Kosten für Sie.'],
it: ['Capitoli','Curiosità','Informazioni','Informativa sulla privacy','Menu','Chiudi menu','Scegli la lingua','Vai al contenuto','Home','Un quaderno per menti curiose','Capire l’universo, un’idea alla volta.','Appunti di fisica gratuiti, dalle leggi del moto alle frontiere della teoria quantistica. Segui la matematica, esplora le idee e continua a chiederti perché.','Inizia a esplorare','Costruisci la tua comprensione, dai fondamenti alle frontiere.','Esplora le domande che continuano a plasmare la fisica.','Open Physics Notes è una raccolta gratuita di appunti universitari di fisica e temi di ricerca. Il nostro obiettivo è la chiarezza, il rigore e l’accessibilità. Tutti i contenuti sono utilizzabili gratuitamente.','Spazio per imparare e meravigliarsi.','Segui i capitoli in ordine oppure una domanda che ti interessa. Equazioni, spiegazioni e letture collegano le singole idee al quadro generale.','Ultimo aggiornamento','Panoramica','Raccogliamo dati minimi per le statistiche del sito. I dati personali non vengono venduti. Possono essere condivisi con i fornitori necessari per statistiche e programmi di affiliazione.','Cookie e preferenze','I cookie possono essere usati per statistiche e link affiliati. Puoi disattivarli nel browser. La lingua è salvata localmente nel browser e si ripristina scegliendo Same as device.','Statistiche','Se attive, le statistiche possono elaborare visualizzazioni e dati aggregati per migliorare i contenuti.','Questo articolo è attualmente disponibile in inglese. Le traduzioni saranno aggiunte gradualmente.','Per approfondire','Questa sezione può contenere link affiliati. Un acquisto tramite questi link può generare una commissione per Open Physics Notes senza costi aggiuntivi per te.'],
es: ['Capítulos','Curiosidades','Acerca de','Política de privacidad','Menú','Cerrar menú','Elegir idioma','Ir al contenido','Inicio','Un cuaderno para mentes curiosas','Entiende el universo, una idea a la vez.','Apuntes gratuitos de física, desde las leyes del movimiento hasta las fronteras de la teoría cuántica. Sigue las matemáticas, explora las ideas y continúa preguntando por qué.','Empieza a explorar','Construye tu comprensión, desde los fundamentos hasta las fronteras.','Explora las preguntas que siguen dando forma a la física.','Open Physics Notes es una colección gratuita de apuntes de física universitaria y temas de investigación. Buscamos claridad, rigor y accesibilidad. Todo el contenido se puede usar gratuitamente.','Espacio para aprender y maravillarse.','Sigue los capítulos en orden o explora una pregunta que te interese. Las ecuaciones, explicaciones y lecturas conectan las ideas con una visión más amplia.','Última actualización','Resumen','Recopilamos datos mínimos para estadísticas básicas del sitio. No vendemos datos personales. Pueden compartirse con los proveedores necesarios para las estadísticas y los programas de afiliación.','Cookies y preferencias','Podemos usar cookies para estadísticas y enlaces afiliados. Puedes desactivarlas en tu navegador. El idioma se guarda localmente y se restablece con Same as device.','Estadísticas','Si están activadas, las visitas y los datos de uso agregados pueden procesarse para mejorar el contenido.','Este artículo está disponible actualmente en inglés. Las traducciones se añadirán gradualmente.','Lecturas adicionales','Esta sección puede incluir enlaces afiliados. Si compras a través de ellos, Open Physics Notes puede recibir una comisión sin coste adicional para ti.'],
'zh-CN': ['章节','探索','关于','隐私政策','菜单','关闭菜单','选择语言','跳至正文','首页','献给好奇心的笔记本','从一个个概念出发，理解宇宙。','免费的物理学笔记，从运动定律到量子理论前沿。跟随数学，探索思想，不断追问为什么。','开始探索','从基础到前沿，逐步建立理解。','深入探索那些仍在塑造物理学的问题。','Open Physics Notes 是免费的讲义式笔记集，涵盖大学物理及前沿课题。我们追求清晰、严谨与易于理解。本站所有内容均可免费使用。','在这里学习，也在这里感受惊奇。','你可以按顺序阅读章节，也可以从感兴趣的问题开始。公式、解释和延伸阅读帮助你将各个概念联系起来。','最后更新','概述','我们仅收集基本网站分析所需的少量数据，不出售个人数据。为运行分析和联盟营销计划，可能会向必要的服务提供商分享数据。','Cookie 与偏好设置','我们可能使用 Cookie 进行分析及联盟链接追踪。你可在浏览器中禁用 Cookie。语言偏好保存在本地浏览器中，选择 Same as device 可恢复设备语言设置。','访问分析','若启用分析，我们可能处理页面浏览量和汇总使用数据，以改善内容质量。','本文目前提供英文版本，翻译将逐步添加。','延伸阅读','本节可能包含联盟链接。通过这些链接购买时，Open Physics Notes 可能获得佣金，你无需支付额外费用。'],
'zh-TW': ['章節','探索','關於','隱私權政策','選單','關閉選單','選擇語言','跳至正文','首頁','獻給好奇心的筆記本','從一個個概念出發，理解宇宙。','免費的物理學筆記，從運動定律到量子理論前沿。跟隨數學，探索思想，不斷追問為什麼。','開始探索','從基礎到前沿，逐步建立理解。','深入探索那些仍在形塑物理學的問題。','Open Physics Notes 是免費的講義式筆記集，涵蓋大學物理及前沿課題。我們追求清晰、嚴謹與易於理解。本站所有內容皆可免費使用。','在這裡學習，也在這裡感受驚奇。','你可以依序閱讀章節，也可以從感興趣的問題開始。公式、解釋與延伸閱讀幫助你將各個概念連結起來。','最後更新','概述','我們僅收集基本網站分析所需的少量資料，不出售個人資料。為執行分析及聯盟行銷計畫，可能向必要的服務提供者分享資料。','Cookie 與偏好設定','我們可能使用 Cookie 進行分析及聯盟連結追蹤。你可在瀏覽器中停用 Cookie。語言偏好儲存在本機瀏覽器中，選擇 Same as device 可恢復裝置語言設定。','瀏覽分析','若啟用分析，我們可能處理瀏覽量與彙總使用資料，以改善內容品質。','本文目前提供英文版本，翻譯將逐步新增。','延伸閱讀','本節可能包含聯盟連結。透過這些連結購買時，Open Physics Notes 可能獲得佣金，你不需支付額外費用。'],
ja: ['章一覧','探究テーマ','このサイトについて','プライバシーポリシー','メニュー','メニューを閉じる','言語を選択','本文へスキップ','ホーム','好奇心のためのノート','ひとつの概念から、宇宙を理解する。','運動の法則から量子論の最前線まで、無料で学べる物理学ノート。数式をたどり、考え方に触れ、「なぜ」を問い続けましょう。','学びはじめる','基礎から最前線まで、理解を積み重ねる。','物理学を今も動かし続ける問いを探究する。','Open Physics Notes は、大学レベルの物理学から最先端のテーマまでを扱う無料の講義形式のノート集です。明快さ、厳密さ、学びやすさを大切にしています。すべてのコンテンツを無料で利用できます。','学ぶ余白。驚きに出会う場所。','章を順番に読み進めても、気になる問いから始めても構いません。数式、解説、参考文献を通じて、それぞれの概念を大きな全体像につなげます。','最終更新','概要','基本的なアクセス解析に必要な最小限のデータを収集します。個人データを販売することはありません。解析やアフィリエイトプログラムの運営に必要な範囲で、サービス提供者にデータを共有する場合があります。','Cookieと設定','アクセス解析やアフィリエイトリンクの追跡にCookieを使用する場合があります。Cookieはブラウザー設定で無効にできます。言語設定はブラウザー内に保存され、Same as deviceを選ぶと端末の言語設定に戻ります。','アクセス解析','解析が有効な場合、コンテンツ改善のためにページ閲覧数や集計された利用データを処理することがあります。','この記事は現在、英語で提供しています。翻訳は順次追加します。','参考文献','このセクションにはアフィリエイトリンクが含まれる場合があります。リンク経由で購入すると、追加のご負担なく Open Physics Notes が紹介料を受け取ることがあります。'],
ko: ['목차','탐구 주제','소개','개인정보 처리방침','메뉴','메뉴 닫기','언어 선택','본문으로 건너뛰기','홈','호기심을 위한 노트','하나의 개념에서 우주를 이해하다.','운동 법칙부터 양자 이론의 최전선까지, 무료로 배우는 물리학 노트입니다. 수학을 따라가고 생각을 탐구하며 계속해서 이유를 물어보세요.','탐구 시작하기','기초부터 최전선까지 이해를 쌓아 보세요.','지금도 물리학을 이끄는 질문을 깊이 살펴보세요.','Open Physics Notes는 대학 물리학부터 첨단 연구 주제까지 다루는 무료 강의식 노트 모음입니다. 명확성, 엄밀성, 접근성을 목표로 합니다. 모든 콘텐츠를 무료로 이용할 수 있습니다.','배움의 공간, 경이로움의 여백.','목차 순서대로 읽거나 관심 있는 질문부터 시작하세요. 수식, 설명, 참고 문헌으로 개별 개념을 더 큰 그림과 연결할 수 있습니다.','최종 수정','개요','기본적인 사이트 분석에 필요한 최소한의 데이터를 수집합니다. 개인정보를 판매하지 않습니다. 분석 및 제휴 프로그램 운영에 필요한 경우 서비스 제공자와 데이터를 공유할 수 있습니다.','쿠키 및 설정','분석 및 제휴 링크 추적에 쿠키를 사용할 수 있습니다. 브라우저에서 쿠키를 비활성화할 수 있습니다. 언어 설정은 브라우저에 저장되며 Same as device를 선택하면 기기 언어로 돌아갑니다.','이용 분석','분석이 활성화된 경우 콘텐츠 개선을 위해 페이지 조회 수와 집계된 이용 데이터를 처리할 수 있습니다.','이 글은 현재 영어로 제공됩니다. 번역은 순차적으로 추가됩니다.','더 읽을거리','이 섹션에는 제휴 링크가 포함될 수 있습니다. 링크를 통해 구매하면 추가 비용 없이 Open Physics Notes가 수수료를 받을 수 있습니다.'],
};
export function messages(locale: Locale): Messages {
  if (locale === 'en') return en;
  return Object.fromEntries(Object.keys(en).map((key, i) => [key, translations[locale][i]])) as Messages;
}
const titles: Record<Locale, string[]> = {
en: ['Newtonian mechanics','Oscillations and waves','Thermodynamics','Electromagnetism','Relativity','Early quantum theory','Quantum mechanics','Quantum field theory','Statistical physics','Condensed matter physics','Cosmology and astrophysics','Frontiers of physics','String theory','Loop quantum gravity','Black hole information paradox','Dark matter','Dark energy','Navier–Stokes equations','Differential geometry'],
fr: ['Mécanique newtonienne','Oscillations et ondes','Thermodynamique','Électromagnétisme','Relativité','Première théorie quantique','Mécanique quantique','Théorie quantique des champs','Physique statistique','Physique de la matière condensée','Cosmologie et astrophysique','Frontières de la physique','Théorie des cordes','Gravitation quantique à boucles','Paradoxe de l’information des trous noirs','Matière noire','Énergie noire','Équations de Navier–Stokes','Géométrie différentielle'],
de: ['Newtonsche Mechanik','Schwingungen und Wellen','Thermodynamik','Elektromagnetismus','Relativitätstheorie','Frühe Quantentheorie','Quantenmechanik','Quantenfeldtheorie','Statistische Physik','Physik der kondensierten Materie','Kosmologie und Astrophysik','Grenzen der Physik','Stringtheorie','Schleifenquantengravitation','Informationsparadoxon schwarzer Löcher','Dunkle Materie','Dunkle Energie','Navier–Stokes-Gleichungen','Differentialgeometrie'],
it: ['Meccanica newtoniana','Oscillazioni e onde','Termodinamica','Elettromagnetismo','Relatività','Prima teoria quantistica','Meccanica quantistica','Teoria quantistica dei campi','Fisica statistica','Fisica della materia condensata','Cosmologia e astrofisica','Frontiere della fisica','Teoria delle stringhe','Gravità quantistica a loop','Paradosso dell’informazione dei buchi neri','Materia oscura','Energia oscura','Equazioni di Navier–Stokes','Geometria differenziale'],
es: ['Mecánica newtoniana','Oscilaciones y ondas','Termodinámica','Electromagnetismo','Relatividad','Teoría cuántica temprana','Mecánica cuántica','Teoría cuántica de campos','Física estadística','Física de la materia condensada','Cosmología y astrofísica','Fronteras de la física','Teoría de cuerdas','Gravedad cuántica de bucles','Paradoja de la información de los agujeros negros','Materia oscura','Energía oscura','Ecuaciones de Navier–Stokes','Geometría diferencial'],
'zh-CN': ['牛顿力学','振动与波','热力学','电磁学','相对论','早期量子理论','量子力学','量子场论','统计物理','凝聚态物理','宇宙学与天体物理','物理学前沿','弦理论','圈量子引力','黑洞信息悖论','暗物质','暗能量','纳维–斯托克斯方程','微分几何'],
'zh-TW': ['牛頓力學','振動與波','熱力學','電磁學','相對論','早期量子理論','量子力學','量子場論','統計物理','凝態物理','宇宙學與天文物理','物理學前沿','弦理論','迴圈量子重力','黑洞資訊悖論','暗物質','暗能量','納維–斯托克斯方程','微分幾何'],
ja: ['ニュートン力学','振動と波','熱力学','電磁気学','相対性理論','初期量子論','量子力学','場の量子論','統計物理学','物性物理学','宇宙論と宇宙物理学','物理学の最前線','弦理論','ループ量子重力','ブラックホール情報パラドックス','暗黒物質','暗黒エネルギー','ナビエ–ストークス方程式','微分幾何学'],
ko: ['뉴턴 역학','진동과 파동','열역학','전자기학','상대성 이론','초기 양자 이론','양자역학','양자장론','통계물리학','응집물질물리학','우주론과 천체물리학','물리학의 최전선','끈 이론','고리 양자 중력','블랙홀 정보 역설','암흑 물질','암흑 에너지','나비에–스토크스 방정식','미분기하학'],
};
export function topicTitle(locale: Locale, kind: 'chapters' | 'curiosities', index: number) { return titles[locale][index + (kind === 'curiosities' ? 12 : 0)]; }

export const sidebarLabels: Record<Locale, { collapse: string; expand: string }> = {
  en: { collapse: 'Collapse sidebar', expand: 'Expand sidebar' },
  fr: { collapse: 'Réduire la barre latérale', expand: 'Développer la barre latérale' },
  de: { collapse: 'Seitenleiste einklappen', expand: 'Seitenleiste ausklappen' },
  it: { collapse: 'Comprimi la barra laterale', expand: 'Espandi la barra laterale' },
  es: { collapse: 'Contraer la barra lateral', expand: 'Expandir la barra lateral' },
  'zh-CN': { collapse: '收起侧边栏', expand: '展开侧边栏' },
  'zh-TW': { collapse: '收合側邊欄', expand: '展開側邊欄' },
  ja: { collapse: 'サイドバーを閉じる', expand: 'サイドバーを開く' },
  ko: { collapse: '사이드바 접기', expand: '사이드바 펼치기' },
};
