// Run while local-preview.mjs is running; only uses the disposable local database.
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import fs from 'node:fs/promises';
const base = 'http://127.0.0.1:3012';
const manifest = JSON.parse(await fs.readFile('lib/discussions/manifest.json', 'utf8'));
const scope = { articleKind: 'curiosities', articleSlug: 'dark-matter', contentLocale: 'en', sectionId: manifest['curiosities/dark-matter/en'][0] };
const payload = { ...scope, displayName: '', content: '<script>window.__discussionXss=1</script>', parentId: null, website: '', requestId: randomUUID() };
const post = (data, origin = base) => fetch(base + '/api/discussions', { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
assert.equal((await post(payload, 'https://evil.test')).status, 403);
assert.equal((await post({ ...payload, content: '  ' })).status, 400);
assert.equal((await post({ ...payload, content: 'x'.repeat(3001) })).status, 400);
assert.equal((await post({ ...payload, website: 'bot' })).status, 400);
assert.equal((await post({ ...payload, sectionId: 'does-not-exist' })).status, 404);
const first = await post(payload); assert.equal(first.status, 201);
const saved = await first.json(); assert.equal(saved.comment.displayName, '');
const replay = await post(payload); assert.equal(replay.status, 201); assert.equal((await replay.json()).comment.id, saved.comment.id);
assert.equal((await post({ ...payload, requestId: randomUUID() })).status, 409);
assert.equal((await post({ ...payload, content: 'Another question', requestId: randomUUID() })).status, 429);
const list = await fetch(base + '/api/discussions?' + new URLSearchParams(scope));
assert.equal(list.status, 200); assert.equal(list.headers.get('x-robots-tag'), 'noindex, nofollow');
assert.ok((await list.json()).items.some(c => c.content === payload.content));
const counts = await fetch(base + '/api/discussions?' + new URLSearchParams({ ...scope, mode: 'counts' }));
assert.ok((await counts.json()).counts[scope.sectionId] >= 3);
const html = await (await fetch(base + '/curiosities/dark-matter')).text();
assert.ok(html.includes('application/ld+json')); assert.ok(html.includes('rel="canonical"'));
assert.ok(html.includes('section-discussion')); assert.ok(!html.includes('window.__discussionXss'));
assert.ok(!html.includes('local-fixture-secret')); assert.ok(!html.includes('local-only-fixture-key'));
console.log('HTTP integration passed: origin, validation, scope, honeypot, post, retry, duplicate, rate limit, lazy loading, metadata, secret isolation.');
